defaults: &defaults
  # postgres
  adapter:      postgresql
  host:         localhost
  min_messages: warning

  # mysql
  # adapter:  mysql2
  # username: root
  # password:
  # socket:   /tmp/mysql.sock

  # sqlite
  # adapter: sqlite3
  # pool:    5
  # timeout: 5000

development:
  <<: *defaults
  database: jamhive_dev

test:
  <<: *defaults
  database: jamhive_test<%= ENV['TEST_ENV_NUMBER'] %>
